spring:
  datasource:
    druid:
      url: jdbc:mysql://172.21.0.2:3306/campus_payment?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      password: root123456
logs:
  path: ./logs/payment/
