spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/campus_payment?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      password: 123456
logs:
  path: ./logs/payment/
